<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
		<string>dedlee</string>
	</array>
	<key>name</key>
	<string>Dedalus</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(initscript|beforeEveryThing|beforeEveryPageTurn|afterEveryThing|afterEveryPageTurn|afterEveryParagraphShown)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s*$</string>
			<key>endCaptures</key>
			<dict/>
			<key>name</key>
			<string>meta.function.dedlee</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(story\.)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{\{(\=|\?\?|\?|\~|\!|\#\#|\#)?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.other.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\}\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.other.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.dedlee</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(story\.)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(when)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>endCaptures</key>
			<dict/>
			<key>name</key>
			<string>meta.function.dedlee</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(story\.)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Object with inventory name</string>
			<key>match</key>
			<string>\b(o\.)(.*)(\s+".*")</string>
			<key>name</key>
			<string>meta.function.dedlee</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Objects and Characters</string>
			<key>match</key>
			<string>\b(o\.|c\.)(.*)</string>
			<key>name</key>
			<string>meta.function.dedlee</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Page, paragraph, with parameters, initscript and before/after actions</string>
			<key>match</key>
			<string>\b(p\.|pg\.|with\.)(.*)</string>
			<key>name</key>
			<string>meta.function.dedlee</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Action</string>
			<key>match</key>
			<string>^\s*(".*")\s*$</string>
			<key>name</key>
			<string>meta.function.dedlee</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.js</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Action</string>
			<key>match</key>
			<string>^\s*(\#.*)</string>
			<key>name</key>
			<string>meta.function.dedlee</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\(\(|\[\[|\{\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.other.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\)\)|\]\]|\]\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.other.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.dedlee</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(.*?)</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.basic.dedalus</string>
	<key>uuid</key>
	<string>3d278171-87aa-470b-b9d6-e5d6e02c961b</string>
</dict>
</plist>
